#+TITLE: Timing Diagrams
#+AUTHOR: Nathan Moos
#+DATE: 2015-09-16

* Timing Delay
  
Two types of delay:
- Gate Delays :: Due to parasitic reactances (gate process time)
- Interconnect Delays :: Due to parasitic resistances (signal travel time)

* Propagation Delay
  
- Rise/fall delay :: The time difference between when the input reaches the
50% mark and the output reaches the 50% mark. Labelled as $t_{pHL}$ or
$t_{pLH}$.

- Rise/fall time :: The amount of time it takes the signal to go from 90% to 10%
                    (or vice versa). Labelled as $t_f$ or $t_r$.

To find the propagation delay $t_p$, you simply average the rise and fall delays.

If there are multiple paths through the circuit, you need to critically inspect 
*all* the paths to find the propagation delay of the entire circuit. The longest
delay in the circuit is called the /critical path/.

* Ring Oscillator
  
By using an odd number of inverters in series that feed back, you can take
advantage of gate delays to produce a binary oscillator. The oscillator's period
is related to the number of gates and the gate delay time.

* Glitches and Hazards
  
In a circuit with /reconvergence/, or a circuit where a signal flows through two
or more different paths, due to unequal delays, an output signal can change for
a brief period, then change back. This is called a /static-1 hazard/.
Static hazards can result in /glitches/, where a signal inexplicably changes for
a short time.

To avoid static hazards, insert another gate to absorb the hazard in front of
the output gate. The output gate should now have 3 inputs. To know what gate to
use, you analyze the circuit to determine how you can affect the output without
changing the meaning of the circuit.

* Lab 2

The 5-input XOR gate's longest delay is from point V to the output of the circuit.

The /ripple carry adder/ (RCA)'s longest delay is along the carry wires.
